# Generated by Django 4.1 on 2022-10-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_evento_remove_receta_id_receta_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripciones',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numerodetelefono', models.CharField(max_length=30)),
            ],
        ),
    ]
