# Generated by Django 4.1 on 2022-10-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_suscripciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sumate',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=50)),
                ('numerodetelefono', models.CharField(max_length=30)),
            ],
        ),
    ]
